const DECK_REQUEST = "DECK_REQUEST";
const DECK_RESPONSE = "DECK_RESPONSE";
const CARD_REQUEST = "CARD_REQUEST";
const CARD_RESPONSE = "CARD_RESPONSE";
const ID_RESPONSE = "ID_RESPONSE";
const BOMB_RESPONSE = "BOMB_RESPONSE";
const MAX_CONNECTION = 2;
module.exports = {
  DECK_REQUEST: DECK_REQUEST,
  DECK_RESPONSE: DECK_RESPONSE,
  CARD_REQUEST: CARD_REQUEST,
  CARD_RESPONSE: CARD_RESPONSE,
  ID_RESPONSE: ID_RESPONSE,
  BOMB_RESPONSE: BOMB_RESPONSE,
  MAX_CONNECTION: MAX_CONNECTION,
  GAME_DECK: require("./game_props")
};
